// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gglekveukcmhdeehdrqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbGVrdmV1a2NtaGRlZWhkcnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTE4MTQsImV4cCI6MjA2NTcyNzgxNH0.lEMo3StpdICxFhO2TA5xQJt5chudzn6a1W5vRcAR9Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);